#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
#matlab -nodisplay -nosplash -r "run('main(7, [5.5 12])'); "
matlab -nodisplay -nosplash -r "main(18,3); exit"
